
services:

  # Nginx
  nginx:
    container_name: nginx                             # Nombre del contenedor
    build:
      context: ./nginx                                # Ubicacion del Dockerfile del microservicio
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html              # Monta la carpeta frontend en Nginx (los cambios son instantaneos)
    ports:
      - "80:80"                                       # Puerto para HTTP
      - "443:443"                                     # Puerto para HTTPS
    networks:
      - pong-net                                      # Red que conecta todos los contenedores
    depends_on:
      - service1                                      # Dependencia de service1
      - db                                            # Dependencia de la base de datos

  # PostgreSQL
  db:
    container_name: postgre                           # Nombre del contenedor
    image: postgres:13
    env_file: .env                                    # Archivo con las variables de entorno
    ports:
      - "5432:5432"                                   # Puerto de PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data               # Volumen donde se guardan los archivos de la base de datos (para que no se borren al desmontar los contenedores)
    networks:
      - pong-net                                      # Red que conecta todos los contenedores

  # MicroServices
  service1:
    container_name: service1                          # Nombre del contenedor
    env_file: .env                                    # Archivo con las variables de entorno
    build:
      context: ./backend/service1                     # Ubicacion del Dockerfile del microservicio
      dockerfile: Dockerfile
    volumes:
      - ./backend/service1:/app                       # Monta la carpeta del microservicio en modo compartido (los cambios son instantaneos)
    ports:
      - "8001:8000"                                   # Puerto de "gunicorn" para las API Request
      - "9001:9000"                                   # Puerto de "daphne" para los WebSockets
    networks:
      - pong-net                                      # Red que conecta todos los contenedores
    depends_on:
      - db                                            # Dependencia de la base de datos

volumes:
  pgdata:                                             # Volumen donde se guardan los archivos de la base de datos (para que no se borren al desmontar los contenedores)

networks:
  pong-net:                                           # Red que conecta todos los contenedores
