global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
  - job_name: 'service1'
    static_configs:
      - targets: ['service1:8000']
