global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules.yaml

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9114']
  - job_name: 'service1'
    static_configs:
      - targets: ['service1:8000']
