groups:
  - name: k-pong_alerts
    rules:
      # Alerta de latencia alta en Nginx
      - alert: HighActiveConnections
        expr: nginx_connections_active > 0  # Ajusta el umbral según tu configuración
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: "High number of active connections on Nginx"
          description: "Nginx has over 100 active connections for more than 1 minute."

      # Alerta de uso de CPU alto en PostgreSQL
      - alert: HighCPUUsagePostgreSQL
        expr: rate(pg_stat_activity_cpu_seconds_total[5m]) > 0.8
        for: 1m
        labels:
          severity: "critical"
        annotations:
          summary: "High CPU usage detected in PostgreSQL"
          description: "PostgreSQL CPU usage is above 80% for more than 1 minute."

      # Alerta de uso de memoria alto en PostgreSQL
      - alert: HighMemoryUsagePostgreSQL
        expr: pg_stat_memory_usage_bytes > 0.8 * pg_stat_memory_total_bytes
        for: 1m
        labels:
          severity: "critical"
        annotations:
          summary: "High memory usage detected in PostgreSQL"
          description: "PostgreSQL memory usage is above 80% for more than 1 minute."
